### ISSUE TITLE
Remove parenthises from event names

### ISSUE THREAD

**Issue by agershun** [MartinMuzatko/riot-cheatsheet#1]
Martin, thank you for the Riot.js cheatsheet.

Could you remove parenthises after event names, because these are not functions:
https://github.com/MartinMuzatko/riot-cheatsheet/blob/master/js/tags/cheatsheet.js#L99-L102

``` html
                    <div>update()</div>
                    <div>updated()</div>
                    <div>mount()</div>
                    <div>unmount()</div>
```

to

``` html
                    <div>update</div>
                    <div>updated</div>
                    <div>mount</div>
                    <div>unmount</div>
```

**Comment by MartinMuzatko** [comment]
Sounds good! Thanks for the suggestion, I will change that.
