### ISSUE TITLE
link in credits section incorrect

### ISSUE THREAD

**Issue by michaelb87** [MartinMuzatko/riot-cheatsheet#4]
Hi,

FYI the https link to happy-css.com pops up a SSL warning and after accepting, it forwards me to your webmail / webhost acc management console.

Cheers

**Comment by MartinMuzatko** [comment]
Hello there!

Thanks a lot for contributing, I wouldn't have noticed that. Yes, the page is not SSL certified yet, so I'll rename it to http://.

Fixed with [#542504a5](https://github.com/MartinMuzatko/riot-cheatsheet/commit/542504a5012942aa8e4fdaaa18e179e407e56d34)
